#!/bin/sh
#
# @RCDIR@/captal-lighttpd: start/stop captal's lighttpd daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/lighttpd
PID=/run/captal-lighttpd.pid
OPTS="-f @ETCDIR@/captal/lighttpd.conf"

case $1 in
start)
	$SSD --start --make-pidfile --pidfile $PID --exec $PROG -- $OPTS
	;;
stop)
	$SSD --stop --remove-pidfile --retry 10 --pidfile $PID
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	$SSD --status --pidfile $PID
	case $? in
	0) echo "$PROG running with pid: $(cat $PID)" ;;
	1) echo "$PROG not running, stale pidfile: $PID" ;;
	3) echo "$PROG not running" ;;
	4) echo "Unable to determine program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# vim:cc=72:tw=70
# End of file.
