#!/bin/sh
#
# /etc/rc.d/captal-dnsserv: start/stop Roque AP DNS Server
#

SSD=/sbin/start-stop-daemon
PROG=/usr/bin/captal-dnsserv
PIDFILE=/var/run/captal-dnsserv.pid
LOGFILE=/var/log/captal-dnsserv.log
OPTS=

case $1 in
start)
	$SSD --start \
		--background \
		--make-pidfile \
		--pidfile $PIDFILE \
		--exec $PROG -- $OPTS >> $LOGFILE 2>&1
	;;
stop)
	$SSD --stop --remove-pidfile --retry 10 --pidfile $PIDFILE
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	$SSD --status --pidfile $PIDFILE
	case $? in
	0) echo "$PROG running with pid: $(cat $PIDFILE)" ;;
	1) echo "$PROG not running, stale pidfile: $PIDFILE" ;;
	3) echo "$PROG not running" ;;
	4) echo "Unable to determine program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
