#!/bin/sh
#
# @RCDIR@/captal-dhcpd: start/stop DHCP daemon
#

. @ETCDIR@/captal/hostapd.conf

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/dhcpd
PID=/run/captal-dhcpd.pid
OPTS="-cf @ETCDIR@/captal/dhcpd.conf -lf @ETCDIR@/captal/dhcpd.leases \
${interface}"

case $1 in
start)
	$SSD --start --pidfile $PID --exec $PROG -- $OPTS
	;;
stop)
	$SSD --stop --remove-pidfile --retry 10 --pidfile $PID
	;;
restart)
	$0 stop
	$0 start
	;;
reload)
	$SSD --stop --signal HUP --pidfile $PID
	;;
status)
	$SSD --status --pidfile $PID
	case $? in
	0) echo "$PROG running with pid: $(cat $PID)" ;;
	1) echo "$PROG not running, stale pidfile: $PID" ;;
	3) echo "$PROG not running" ;;
	4) echo "Unable to determine program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|reload|status]"
	;;
esac

# vim:cc=72:tw=70
# End of file.
